language: go

go:
  - 1.6

install:
  - echo "install fzp tool"
  - go get github.com/fritzing/fzp/bin/fzp

script:
  - $GOPATH/src/github.com/fritzing/fzp/bin/fzp -v
  - fzp -v

  - $GOPATH/src/github.com/fritzing/fzp/bin/fzp validate -d $GOPATH/src/github.com/fritzing/fritzing-parts/core
